"""Dynamic state for comic creation sessions.

This module manages the evolving state of a comic creation session.
The LLM dynamically creates locations and characters as the story progresses,
and this module stores and tracks them.
"""

from datetime import datetime

from pydantic import BaseModel, Field

from .static_config import StaticConfig


class DynamicLocation(BaseModel):
    """A location created by the LLM during the story."""

    id: str = Field(description="Unique identifier (generated by LLM)")
    name: str = Field(description="Location name")
    description: str = Field(description="Brief description (1-2 sentences: setting type, key atmosphere)")
    first_appeared_panel: int = Field(description="Panel number when this location was introduced")


class DynamicCharacter(BaseModel):
    """A character created by the LLM during the story."""

    id: str = Field(description="Unique identifier (generated by LLM)")
    name: str = Field(description="Character's name")
    description: str = Field(description="Brief description (1-2 sentences: 2-3 key visual features + 1 personality trait)")
    current_location: str = Field(default="", description="Where this character currently is")
    first_appeared_panel: int = Field(description="Panel number when this character was introduced")


class ComicPanel(BaseModel):
    """A single panel in the comic strip."""

    panel_number: int = Field(description="Panel number in sequence")
    narrative: str = Field(description="The narrative text for this panel")
    image_path: str | None = Field(default=None, description="Path to generated image")
    player_action: str = Field(default="", description="What the player did")
    timestamp: datetime = Field(default_factory=datetime.now)


class NarrativeState(BaseModel):
    """Record of the comic story."""

    panels: list[ComicPanel] = Field(default_factory=list)
    rolling_summary: str = Field(
        default="The story has just begun.",
        description="Condensed summary of the story so far"
    )
    current_scene: str = Field(
        default="",
        description="Description of current scene"
    )


class WorldState(BaseModel):
    """Current state of the story world.

    The LLM dynamically creates locations and characters as the story evolves.
    These are stored here along with the current narrative position.
    """

    # Current position in the story
    current_location_id: str = Field(default="starting_location", description="Current location ID")
    current_location_name: str = Field(default="", description="Current location name")

    # Dynamic entities created by the LLM
    locations: list[DynamicLocation] = Field(
        default_factory=list,
        description="Locations discovered/created during the story"
    )
    characters: list[DynamicCharacter] = Field(
        default_factory=list,
        description="Characters introduced during the story"
    )

    # Main character info (from blueprint)
    main_character_name: str = Field(default="", description="Name of the main character")
    main_character_description: str = Field(default="", description="Description of the main character")

    class Config:
        arbitrary_types_allowed = True

    def get_location_by_id(self, location_id: str) -> DynamicLocation | None:
        """Get a location by ID."""
        for loc in self.locations:
            if loc.id == location_id:
                return loc
        return None

    def get_character_by_id(self, character_id: str) -> DynamicCharacter | None:
        """Get a character by ID."""
        for char in self.characters:
            if char.id == character_id:
                return char
        return None

    def get_characters_at_location(self, location_id: str) -> list[DynamicCharacter]:
        """Get all characters currently at a location."""
        return [char for char in self.characters if char.current_location == location_id]

    def add_location(self, location: DynamicLocation) -> None:
        """Add a new location to the world."""
        if not self.get_location_by_id(location.id):
            self.locations.append(location)

    def add_character(self, character: DynamicCharacter) -> None:
        """Add a new character to the world."""
        if not self.get_character_by_id(character.id):
            self.characters.append(character)


class RenderState(BaseModel):
    """Scene information for image generation. Combined with the comic's visual_style."""

    scene_setting: str = Field(default="", description="Description of the current scene/location")
    characters_present: list[str] = Field(
        default_factory=list,
        description="Characters in the scene with brief descriptions"
    )
    objects_visible: list[str] = Field(
        default_factory=list,
        description="Notable objects visible in the scene"
    )
    current_action: str = Field(
        default="",
        description="What is happening in this panel"
    )

    def to_image_prompt(self, visual_style: str = "comic book style") -> str:
        """Generate an image prompt from the render state."""
        parts = [visual_style]

        if self.scene_setting:
            parts.append(f"Setting: {self.scene_setting}")

        if self.characters_present:
            chars = ", ".join(self.characters_present[:3])
            parts.append(f"Characters: {chars}")

        if self.current_action:
            parts.append(f"Action: {self.current_action}")

        return ". ".join(parts)


class MetaInfo(BaseModel):
    """Technical metadata for the session."""

    session_id: str = Field(default="", description="Unique session identifier")
    panel_count: int = Field(default=0, description="Number of panels created")
    started_at: datetime = Field(default_factory=datetime.now)
    last_updated: datetime = Field(default_factory=datetime.now)


class ComicState(BaseModel):
    """Complete state for a comic creation session."""

    narrative: NarrativeState = Field(default_factory=NarrativeState)
    world: WorldState = Field(default_factory=WorldState)
    render: RenderState = Field(default_factory=RenderState)
    meta: MetaInfo = Field(default_factory=MetaInfo)

    @classmethod
    def initialize_from_config(cls, config: StaticConfig, session_id: str = "") -> "ComicState":
        """Create initial state from configuration.

        The blueprint only defines the starting location and main character.
        All other locations and characters will be created dynamically by the LLM.
        """
        import uuid

        if not config.blueprint:
            raise ValueError("Cannot initialize without blueprint")

        blueprint = config.blueprint

        # Initialize world state with starting location and main character
        starting_loc = blueprint.starting_location
        main_char = blueprint.main_character

        # Create the starting location as a DynamicLocation
        initial_location = DynamicLocation(
            id="starting_location",
            name=starting_loc.name,
            description=starting_loc.description,
            first_appeared_panel=0
        )

        world = WorldState(
            current_location_id="starting_location",
            current_location_name=starting_loc.name,
            locations=[initial_location],
            characters=[],  # No characters yet - LLM will introduce them
            main_character_name=main_char.name,
            main_character_description=main_char.description
        )

        # Initialize narrative state
        narrative = NarrativeState(
            panels=[],
            rolling_summary=f"{blueprint.synopsis}",
            current_scene=starting_loc.description
        )

        # Initialize render state
        render = RenderState(
            scene_setting=starting_loc.description,
            characters_present=[f"{main_char.name}: {main_char.description}"],
            objects_visible=[],
            current_action="The scene opens"
        )

        # Meta info
        meta = MetaInfo(
            session_id=session_id or str(uuid.uuid4()),
            panel_count=0,
            started_at=datetime.now(),
            last_updated=datetime.now()
        )

        return cls(
            narrative=narrative,
            world=world,
            render=render,
            meta=meta
        )

    def add_panel(self, player_action: str, narrative: str, image_path: str | None = None) -> ComicPanel:
        """Add a new panel to the comic strip."""
        self.meta.panel_count += 1
        panel = ComicPanel(
            panel_number=self.meta.panel_count,
            narrative=narrative,
            image_path=image_path,
            player_action=player_action
        )
        self.narrative.panels.append(panel)
        self.meta.last_updated = datetime.now()
        return panel

    def get_recent_panels(self, count: int = 5) -> list[ComicPanel]:
        """Get the most recent panels."""
        return self.narrative.panels[-count:]

    def get_all_panels(self) -> list[ComicPanel]:
        """Get all panels in the comic strip."""
        return self.narrative.panels

    def get_context_summary(self) -> str:
        """Get a summary of current state for the LLM."""
        lines = [
            f"CURRENT STORY STATE (Panel {self.meta.panel_count}):",
            f"",
            f"Main Character: {self.world.main_character_name} - {self.world.main_character_description}",
            f"",
            f"Current Location: {self.world.current_location_name}",
            f"",
            f"Story So Far: {self.narrative.rolling_summary}",
            f"",
            f"Current Scene: {self.narrative.current_scene}",
        ]

        # List known locations
        if self.world.locations:
            lines.append("")
            lines.append("Known Locations:")
            for loc in self.world.locations:
                lines.append(f"  - {loc.name}: {loc.description}")

        # List known characters (introduced by LLM)
        if self.world.characters:
            lines.append("")
            lines.append("Characters in Story:")
            for char in self.world.characters:
                loc_info = f" (at: {char.current_location})" if char.current_location else ""
                lines.append(f"  - {char.name}: {char.description}{loc_info}")

        # Recent panels
        if self.narrative.panels:
            lines.append("")
            lines.append("Recent Panels:")
            for panel in self.get_recent_panels(3):
                lines.append(f"  Panel {panel.panel_number}: {panel.narrative}")

        return "\n".join(lines)
